### PR TITLE
Mature Ages

### PR DESCRIPTION
**Pull request by Hekzder**
After an argument on Discord, a compromise was reached to just increase ages of species to match their proper maturity ages. I believe this should cover all the ages that need an increase, if anyone thinks a species is missing an age increase, shout it out. I'm not very well versed in species lore. 

Unathi Min Age: 25
Skrell Min Age: 18
GAS Min Age: 10
Tajaran Min Age: 18

### CODE REVIEW

**Comment by BurpleBineapple** [comment]
Legality is lit

**Comment by Sgtwok** [comment]
Unathi are a strange beast thanks to the way their society works, 25 is the average for them though it can vary by clan.

**Comment by Hekzder** [comment]
> Unathi are a strange beast thanks to the way their society works, 25 is the average for them though it can vary by clan.

In the same way that ages of maturity can vary based on country or culture in the real world, using the higher end of the overall average is generally the best way to go, hence 25 for Unathi.

**Comment by Kaksisilma** [comment]
Skrell can stay at 18 since that's the age where they become Qrii'Mogs.

**Comment by Hekzder** [comment]
> Skrell can stay at 18 since that's the age where they become Qrii'Mogs.

Currently the min age is 19. It's pretty inconsequential to me personally whether this becomes 18 or 20, but I do think it should change 1 year up or down. 19 is a weird and non-sensical limbo.

**Comment by listerla** [comment]
It should be 18. That's when Skrell pick up work, and it doesn't really make sense for them not to be at least a janitor or something at that point.

**Comment by Hekzder** [comment]
Skrell min age is now 18, down from the nonsensical 19. 

I'm open to a lower min age for Unathi than currently proposed if it's an issue, but I do think 18 min age is honestly low considering how Unathi age and mature, and what would make sense in regards to service on the Dagon or various off-ship roles.

**Review by BurpleBineapple — APPROVED** [review]
Gonnaaaaaaa go ahead and merge this lad here

**Comment by ProfessorPopoff** [comment]
God speed.

**Pull request merged**
