### PR TITLE
Green into Urban

### PR DESCRIPTION
**Pull request by Lamasmaster**
Changes marine green fatigues for urban as per that option having majority in the poll

https://docs.google.com/forms/d/e/1FAIpQLSc_tvKqD1ygqVOSthCKwMijrx7JH8-sxaS056_V5G4xfUMuYA/viewanalytics

### CODE REVIEW

**Comment by Sgtwok** [comment]
There will need to be some rework for unathi sprites but for now, navy has unathi sprites.

**Comment by Lamasmaster** [comment]
> There will need to be some rework for unathi sprites but for now, navy has unathi sprites.

Ok if you want urban sprites make them, I don´t have patience or dedication to make them.

**Review by io-util — APPROVED** [review]

**Comment by io-util** [comment]
> There will need to be some rework for unathi sprites but for now, navy has unathi sprites.

There are a lot of "missing" or well, "not properly working" Unathi Sprites, but at least this is out of the way for now, can always deal with fixing and or adding Unathi Sprites at a later time.

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
You'll need to change the uniform_marine_corps file as well to switch all the green gear in the vendor when urban coloured gear.

**Review by BurpleBineapple — APPROVED** [review]
Shouuuld be fine.

**Pull request merged**
