### PR TITLE
new exoplanet ruins

### PR DESCRIPTION
**Pull request by gilvian**
https://github.com/VestaOfOrion/Vesta.Bay/pull/121 < This PR but working :)

🆑 Gibong
rcsadd: Adds 2 new exo-planet ruins into the exoplanet generation pool
/:cl:

### CODE REVIEW

**Review by BurpleBineapple — APPROVED** [review]
Looks good to me

**Review by Superhats — APPROVED** [review]
Good Stuff

**Comment by Superhats** [comment]
Just needs a changelog and you're good to go

**Comment by gilvian** [comment]
> Just needs a changelog and you're good to go

arent we using the automatic bay changelog generator with the :cl: thing?

**Comment by gilvian** [comment]
how

**Pull request merged**
