### PR TITLE
Rank Overhaul

### PR DESCRIPTION
**Pull request by Hekzder**
For a TLDR and those wanting to see the changes without looking through changed files, [look here. ](https://docs.google.com/document/d/1rMGzEorNXVTd__OTK9nZXBrgv9MlZ5Zqw7u8hPQX2yE/edit?usp=sharing)

But basically, this PR takes a look at ranks and branch options and changes them around a fair bit. The biggest and likely most controversial points are as follows:

- No more O-5 for CMO and CSO.
- No more O-4 for Physician and Scientist. 
- Senior Researcher is gone, reduced to atoms. 
- No more O-2 for Bridge Officer.
- SMC Attache is gone in favor of re-adding MSEA.

We also have an overabundance of O-4+ personnel. In current Vesta, assuming _everyone_ chooses the highest rank available to them, we have more than **twelve** O-4+ personnel, of which only four of them are either a department head or the XO/CO. CMO and CSO are toned down from O-5 to avoid situations where the CMO or CSO potentially outranks the XO and to make chain of command **as clear as possible**. I'm not saying that O-5 CMOs and CSOs regularly try to over-rule and boss around an O-4 XO, but I've seen it happen, and the potential for it to happen just shouldn't be there. 

Senior Researcher, after talking with some Science players, doing some thinking myself, and with these rank changes, simply does not have a good place in Vesta as it stands now. It's a weird middle man role for a department that does not need or benefit from having a middle man, and with the rank changes and such, it's even harder to justify them having a place. 

The changelog is pretty much just the document linked at the top of the PR. Please leave comments, suggestions, coping, questions, etc. in the comments below or ping/DM me on Discord, Hekzder#7857. Since I don't explain _every_ change I've done here, only the controversial ones, I'm more than happy to explain my reasoning for other changes or go more in depth on anything I've already explained.

### CODE REVIEW

**Comment by Sgtwok** [comment]
How about no?
No, seriously, can we STOP removing marine content?

**Comment by Hekzder** [comment]
> How about no?
> No, seriously, can we STOP removing marine content?

It's not really "content", it's a minor trimming of Marines from top level Command roles on a Navy ship. Yes it's a joint operation, that's part of why I want to have Attache cemented as a coordinating officer for SMC. But at the end of the day, it's still predominantly a Naval ship where most of the upper level Command staff should be Naval officers. The fact that the Dagon "used to be an SCG ship" is completely irrelevant, it's now owned and chiefly operated by NTEF, therefore you'd expect them to have most department heads and high ranking officers be their own people, not Marines that are only temporarily stationed on the ship. 

I understand that what to do with Attache and Attache as a role entirely is divisive and controversial and muddy, but at the very least I'd like to try out Attache as a coordinating officer for Marines and see how it goes. If it ends up panning out poorly, then it can be changed. But I don't think it's such a horrible idea that it shouldn't even be tried.

**Comment by Hekzder** [comment]
SMC changes will be gone soon, reduced to atoms.

SMC Attache removed in favor of MSEA being re-added. Branch option of normal SEA will then be gone.

**Comment by Hekzder** [comment]
It's really just a rank overhaul at this point + MSEA, so I retitled accordingly.

**Comment by Anton-Kr** [comment]
absolutely based

**Comment by BurpleBineapple** [comment]
Not going to take the risk with hitting merge on this anytime soon, but I will say it's a very valid PR. This rank structure would match the chain of command almost exactly compared to the potato ranks we have now.

Still not going to full send it, but y'know, my two cents

**Comment by Hekzder** [comment]
Fixes merge conflict from the Bay update PR, also the Bay update PR apparently removed the Nurse alt-title, probably on accident. But this PR re-adds it plus another alt-title for fun. 

This is pretty much good to merge again once checks pass. I still think it's a PR that overall makes sense in terms of bringing our ranks more in line with our actual chain of command and toning down on the currently absurd amount of senior officer roles we have on the Dagon. If and when this is merged I'll probably start work on more job related PRs like opening up jobs to more branches and even potentially adding some new ones, that's probably just going to be my preferred specialty for the time being. 

Also worth pointing out to everyone that this PR no longer touches the SMC at all besides removing the very confusing and horrible Attache role in favor of just having it be the MSEA again. There's a lot of downvotes that are probably just from when this PR originally was removing SMC from some roles, but that is no longer the case for this PR at all.

**Review by BurpleBineapple — APPROVED** [review]
Changes approved

**Comment by Alanii** [comment]
This should not have been merged without further scrutiny. 

Adjusting the Command ranks is fine, but the removal of a rank from Bridge Officer makes no sense. Bridge Officer isn't supposed to be a 'one rank' role.

You should be able to progress. O1 serves as the first officer rank, while O2 serves as the denotion of a veteran Bridge Officer.

Forcing all Bridge Officers to be just one rank does not allow Command teams to determine who could be more experienced than the prior.

Regardless or not of the 'bridge officer alwasy attempt to enforce power trip' that should be fixed through gameplay, and people throwing them the book of regulations. Not removing ranks.

**Pull request merged**
