### PR TITLE
Turret Addition v2

### PR DESCRIPTION
**Pull request by Zulu0009**
Hopefully adds turrets idk I hope it works

### CODE REVIEW

**Review by io-util — APPROVED** [review]
Maps look fine.

**Comment by io-util** [comment]
Was this compiled and tested @Zulu0009? I mean it _should be fine_.

**Comment by Zulu0009** [comment]
> 
> 
> Was this compiled and tested @Zulu0009? I mean it _should be fine_.

I most definitely did not test it but I am hoping very hard that it works so that's enough right

**Comment by io-util** [comment]
> I most definitely did not test it but I am hoping very hard that it works so that's enough right

It's just a few map changes and they look alright, so it most definitely should be fine, just double checking, usually you should test stuff before making a Pull Request about it.

**Comment by Zulu0009** [comment]
> It's just a few map changes and they look alright, so it most definitely should be fine, just double checking, usually you should test stuff before making a Pull Request about it.

I tried to run a server to test them but I got a headache tbh, this is just about the biggest map change I've done so I sure hope it works

**Pull request merged**
