### PR TITLE
Adds CO Ammo back to the autolathe

### PR DESCRIPTION
**Pull request by Vizoplez**
Title. This was missed in the full vesta.bay port.

### CODE REVIEW

**Comment by gilvian** [comment]
Hi can i say this isn't the greatest idea?

I think on old Hestia code it was disabled since COs would just run up to the autolathe and go "mmm more ammo time" and load up 5 extra mags so they can validhunt, maybe another way to get this type, like through cargo?

**Comment by Vizoplez** [comment]
> Hi can i say this isn't the greatest idea?
> 
> I think on old Hestia code it was disabled since COs would just run up to the autolathe and go "mmm more ammo time" and load up 5 extra mags so they can validhunt, maybe another way to get this type, like through cargo?

https://github.com/VestaOfOrion/Vesta.Bay/pull/151#issuecomment-751693243

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
Changelog missing

**Review by BurpleBineapple — APPROVED** [review]
The ammo costs enough that printing more than 1 will tick off security, so good luck I suppose.

Approved

**Pull request merged**
