### PR TITLE
Adds SMC and NTEF to Lab Tech. Adds NTEF to Salvage Tech

### PR DESCRIPTION
**Pull request by Hekzder**
After some discussion, this PR is just going to add SMC and NTEF to Lab Tech, and NTEF to Salvage Tech.

### CODE REVIEW

**Comment by BurpleBineapple** [comment]
Roboticist is restricted to contractor/NTEF as with all science roles. Had it still been under engineering I would agree, but as it is now I don't think we need add SMC to the department

**Comment by Hekzder** [comment]
> Roboticist is restricted to contractor/NTEF as with all science roles. Had it still been under engineering I would agree, but as it is now I don't think we need add SMC to the department

The idea is that Roboticist will be moved to another department to allow for SMC to be added. I agree SMC should not be added to Science. My most likely first move will be moving it to Engineering, if that's alright with you and others. Personally I think Roboticist fits more in Engineering overall anyways.

**Comment by Hekzder** [comment]
This is good for review/merge now. Just adds NTEF and SMC to Lab Tech and NTEF to Prospector. Mildly adjusts the descriptions and such of each of those jobs to accordingly fit the wider variety of branches. Nothing controversial or complax at all like the PR was originally planning.

**Review by Superhats — APPROVED** [review]
Fine by me.

**Comment by Superhats** [comment]
Gonna need a second opinion, don't want to touch more branch changes on my own.

**Comment by BurpleBineapple** [comment]
(also yes this means approved by lore guys)

**Pull request merged**
