### PR TITLE
Makes the 454 not a holdout pistol(TM)

### PR DESCRIPTION
**Pull request by Vizoplez**
Title

### CODE REVIEW

**Comment by Alanii** [comment]
> Title

Can you elaborate more?

**Comment by Vizoplez** [comment]
> > Title
> 
> Can you elaborate more?

as per main-dev discussion, the holdout pistol does 40 brute with a higher AP. As it stood; the Final Argument(The weapon the XO got) was made a direct upgrade that was not only easier to get ammo for, but less expensive and more accurate. This buffs it up to be equivalent. The nerfs were far too hard according to a few devs. So.

**Comment by Alanii** [comment]
> as per main-dev discussion, the holdout pistol does 40 brute with a higher AP. As it stood; the Final Argument(The weapon the XO got) was made a direct upgrade that was not only easier to get ammo for, but less expensive and more accurate. This buffs it up to be equivalent. The nerfs were far too hard according to a few devs. So.

Ok, thanks.

**Review by BurpleBineapple — APPROVED** [review]
Approved

**Pull request merged**
