### PR TITLE
Point and resist adventure

### PR DESCRIPTION
**Pull request by Firefox13**
Adds hollowing hotkeys:
CTRL+WASD to ~~speeeeeeeeeen~~ rotate.
ALT+WASD to lock face direction.
CTRL+SHIFT+WASD to pixel shift character.
B to resist.
SHIFT+MMB to point at **[X]**

### CODE REVIEW

**Comment by Agateophobia** [comment]
why not just SHIFT+MMB to point?

**Comment by Firefox13** [comment]
> 
> 
> why not just SHIFT+MMB to point?

Old one was CTRL+SHIFT+MMB, don't see a reason to change it as everyone's accustomed to it already?

**Comment by Agateophobia** [comment]
WHAT, IT WASN'T SHIFT+MMB? NANI

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
CTRL+Direction already spins. ALT+Direction already locks. Please remove those changes

**Comment by Hekzder** [comment]
Also it was SHIFT + MMB, not CTRL + SHIFT + MMB. Not sure where this idea came from, maybe both worked, but SHIFT + MMB is obviously superior.

**Comment by Agateophobia** [comment]
purple, it doesn't spin you if you use WSAD, CTRL+ARROWKEYS spins you, the pr was supposed to make it so CTRL+WSAD also spins you (i might be autistic tho)

**Comment by BurpleBineapple** [comment]
> purple, it doesn't spin you if you use WSAD, CTRL+ARROWKEYS spins you, the pr was supposed to make it so CTRL+WSAD also spins you (i might be autistic tho)

My mistake then. But as for the pointing "SHIFT+MMB" seems better than ctrl+shift

**Comment by Firefox13** [comment]
> 
> 
> > purple, it doesn't spin you if you use WSAD, CTRL+ARROWKEYS spins you, the pr was supposed to make it so CTRL+WSAD also spins you (i might be autistic tho)
> 
> My mistake then. But as for the pointing "SHIFT+MMB" seems better than ctrl+shift

the truth is, I'm retarded - it is already shift+MMB. It's just me always holding CTRL+SHIFT+MMB for some reason, and the hotkey for it is just shift+MMB.

**Review by io-util — APPROVED** [review]

**Pull request merged**
