### PR TITLE
Restores power production of ascent fusion stack to (un)reasonable levels

### PR DESCRIPTION
**Pull request by Sun-Soaked**
Changelog:
- Restores Mantid Fusion Stack power production to pre vestabay levels. The national nightmare is over.

My first proper(independent) pr! Watch me fuck it up somehow.

### CODE REVIEW

**Review by io-util — CHANGES_REQUESTED** [review]
Please add a changelog YAML file to your Pull Request, since we still do not have our changelog generation through PR description set up.

Refer to https://github.com/VestaOfOrion/Vesta.Bay/blob/dev/html/changelogs/example.yml if you do not know how to.

**Comment by Sun-Soaked** [comment]
...I managed to fuck it up. There's the changelog

**Comment by io-util** [comment]
> ...I managed to fuck it up. There's the changelog

`html/changelogs/memedhams-PR-1.yml` should be `html/changelogs/memedhams-PR-124.yml` since this is Pull Request #124.

**Review by BurpleBineapple — APPROVED** [review]
Looks good to me

**Pull request merged**
