### PR TITLE
[WIP] The great Kidan port of 2021

### PR DESCRIPTION
**Pull request by Superhats**
This is a port of Kida, a species of feudal spess bugs hailing from the world-renowned paradise station.
Currently in a HEAVY state of WIP, as the species is currently a human reskin without any lore.
image
This also adds several new antennae, along with one head tattoo to the genemods option.
And, while I'm at it, I've commented out a bunch of ears that had no sprite.
To-do:

- [x] Port sprites and sprite accessories.
- [x] Break sprites and sprite accessories in the process.
- [ ] Implement unique mechanics
- [ ] Implement unique lore
- [ ] Fix sprites and sprite accessories

### CODE REVIEW

**Comment by ghost** [comment]
These sprites look like humanoid GAS.

Perhaps they could be Small Unarmored Bipedals? SUBs?

**Comment by Agateophobia** [comment]
> Perhaps they could be Small Unarmored Bipedals? SUBs?

please do

**Comment by ghost** [comment]
> > Perhaps they could be Small Unarmored Bipedals? SUBs?
> 
> please do

For the two rounds I played MSQ, I referred to humans as SUBs, so it's definitely a useful term.

**Comment by Superhats** [comment]
I don't plan on making them related to serpentids, regardless of any puns.

**Comment by Superhats** [comment]
Need to reopen

**Pull request closed without merging**
