### PR TITLE
Removes most SCG logos and puts NTEF logos on the shuttles

### PR DESCRIPTION
**Pull request by Lamasmaster**
Had to make 2 PRs because branchman bad

### CODE REVIEW

**Comment by BurpleBineapple** [comment]
There's some SCG Logos on all the airlocks on the entire ship. Please change those too.

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
^

**Comment by Lamasmaster** [comment]
> There's some SCG Logos on all the airlocks on the entire ship. Please change those too.

All logos changed and also fixed briefing room floor decals

**Comment by BurpleBineapple** [comment]
image
This logo is still in the OFD
image
Remove this logo as well, or move it next to the door to match the SCG Representative office

**Comment by BurpleBineapple** [comment]
Also, the Attache office should be made of reinforced walls. All command offices are reinforced.

**Comment by Lamasmaster** [comment]
> image
> This logo is still in the OFD
> image
> Remove this logo as well, or move it next to the door to match the SCG Representative office

Fixed now

**Review by BurpleBineapple — APPROVED** [review]

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
Edits to the SMC Attache office I said on discord

**Review by BurpleBineapple — APPROVED** [review]
Approved

**Pull request merged**
