### PR TITLE
Updates the repository to current bay.

### PR DESCRIPTION
**Pull request by Kaksisilma**
Does exactly what it says on the title.

This is probably going to break horribly.

### CODE REVIEW

**Comment by Alanii** [comment]
Return code/datums/music_tracks/Torch.dm

The song name to the original. It isn't a big deal regarding it being 'Torch' but the song name must not change.

**Review by io-util — CHANGES_REQUESTED** [review]
`UNIT_TEST ##: /datum/gear/tactical/pcarrier/navy - /obj/item/clothing/suit/armor/pcarrier/ipc ('Black ipc plate carrier'): Was not a path of /obj/item/clothing/suit/armor/pcarrier/navy.`

`UNIT_TEST ##: /datum/gear/tactical/pcarrier/navy - /obj/item/clothing/suit/armor/pcarrier ('Black plate carrier'): Was not a path of /obj/item/clothing/suit/armor/pcarrier/navy.`

`UNIT_TEST ##: /datum/gear/tactical/pcarrier/navy - /obj/item/clothing/suit/armor/pcarrier/blue/ipc ('Blue ipc plate carrier'): Was not a path of /obj/item/clothing/suit/armor/pcarrier/navy.`

`UNIT_TEST ##: /datum/gear/tactical/pcarrier/navy - /obj/item/clothing/suit/armor/pcarrier/blue ('Blue plate carrier'): Was not a path of /obj/item/clothing/suit/armor/pcarrier/navy.`

`UNIT_TEST ##: /datum/gear/tactical/pcarrier/navy - /obj/item/clothing/suit/armor/pcarrier/green/ipc ('Green ipc plate carrier'): Was not a path of /obj/item/clothing/suit/armor/pcarrier/navy.`

`UNIT_TEST ##: /datum/gear/tactical/pcarrier/navy - /obj/item/clothing/suit/armor/pcarrier/green ('Green plate carrier'): Was not a path of /obj/item/clothing/suit/armor/pcarrier/navy.`

`UNIT_TEST ##: !!! FAILURE !!! [LOADOUT: Gear path tweaks shall be of gear path.]: 6 /datum/gear_tweak/path definitions had invalid paths.`

And please remove `scripts/validateTestingContainsAllMaps.sh` again, we will add it back once it's in the CI workflow.

**Comment by Vizoplez** [comment]
@vhbraz please revert bays meddling with off-ships; as it disables many (as far as I have heard) and otherwise nerfs others to unplayability. honk.

**Comment by Kaksisilma** [comment]
I wish I knew how to squash commits.

@Superhats Should be good for review.

**Review by Superhats — APPROVED** [review]
Looks alright.

**Pull request merged**
