### PR TITLE
Additional Alt-Titles

### PR DESCRIPTION
**Pull request by Agateophobia**
yeah, like the pr title says, it adds Junior Researcher and Coroner alt-title

### CODE REVIEW

**Comment by gilvian** [comment]
Junior-Researcher

isn't that just Intern/Research Assistant?

**Comment by Agateophobia** [comment]
Nah, it's Scientist alt-title, so Hans doesn't feel bad with his promotion, tbh

**Comment by gilvian** [comment]
So this really is just an update pandering to one person with a pointless alt-title?

**Comment by Agateophobia** [comment]
actually ya may be right, I'll add it to research assistant

**Comment by BurpleBineapple** [comment]
As stated in previously, we want to avoid bloat titles as much as possible. Snowflake job titles like "junior researcher", "EVA technician", "t a c t i c a l o f f i c e r" are to be avoided and contribute very little. This isn't to you directly, but just *generally* we're not accepting alt-titles as an addition unless it's something that changes the role significantly, like Union Representative vs Corporate Liason

**Pull request closed without merging**
