### PR TITLE
New Ascent Seedship

### PR DESCRIPTION
**Pull request by Kaksisilma**
New Ascent Ship.

Changes are on the changelog file, but in summary, this adds a completely revamped Ascent ship, aswell as some flavor items.

bullet
Capture

### CODE REVIEW

**Comment by Kaksisilma** [comment]
Should probably be good for review & merging now.

inb4 CI fails

**Comment by io-util** [comment]
Was this tested by you, @vhbraz?

**Comment by Kaksisilma** [comment]
> Was this tested by you, @vhbraz?

To an extent, yes.
Both shuttles (main ship and the smol one) are fully functional and capable of multi-z
scrubber/vent placements are all fine, so are APCs and powerlines.
Airlocks are functional
Both shuttles dock with the dagon successfuly
Armory turrrets and other stuff work.
etc...

The only problem I suspect that might arise is there not being enough equipment for Ascent, or maybe I forgot something important. In either case, because I don't play ascent, I asked Superhats to take a look for me and they told me it was good.

**Review by wb13 — APPROVED** [review]
Looks good. Sorry for the wait.

**Comment by Kaksisilma** [comment]
Can't muster the energy to continue working on this or figure out why did those runtimes suddenly start happening. I'll close this but idk, feel free to use it if you want to.

**Comment by Vizoplez** [comment]
its due to the silicon_Restriction var, just strip it from your airlocks.

**Pull request closed without merging**
