### PR TITLE
Tablet: sprite on hand.

### PR DESCRIPTION
**Pull request by Alejodbort2**
Adds sprites when holding the tablet, to make it look more cool and nice.

image
image

## Changelog
:cl:
**add:** Sprite on hand for the tablet (common), left and right hand,
**add:** Sprite on hand for the tablet (command), left and right hand.
/:cl:

### CODE REVIEW

**Review by Superhats — APPROVED** [review]
Looks good. Changelog, please.

**Comment by Alejodbort2** [comment]
Sorry, there you go.

**Comment by BurpleBineapple** [comment]
You'll need to make one manually. Look in the "html" folder in your repository then check "changelog"

There should be an example file there. Make a copy and fill out your changes

**Comment by Alejodbort2** [comment]
Uuh, it's fine now?

**Pull request merged**
