### PR TITLE
Adjusts 454 to be more reasonable

### PR DESCRIPTION
**Pull request by Vizoplez**
Title. Makes 454 have slightly higher AP at a modest damage reduction. Because people whine.

### CODE REVIEW

**Comment by Keekenox** [comment]
What is wrong with the gun currently?

**Comment by Vizoplez** [comment]
> What is wrong with the gun currently?

Far too strong. Refer to my other PR as adjustments for it.

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
Changelog missing

**Comment by Lamasmaster** [comment]
15 missing damage doesnt really make it weaker if anything it makes it even better as a tool for validhunting considering its almost mirroring stats with assault rifle and bulldog, the weapon was also intended as an execution tool rather than actual weapon you should use.

**Review by BurpleBineapple — APPROVED** [review]
Approved following yesterday's discussion

**Pull request merged**
