### PR TITLE
Updates to HCM rigs and a few voidsuits

### PR DESCRIPTION
**Pull request by CRISPR-core**
_Also known as "That One Thing Capesh Wanted For Months."_

[Insert Thanos doing it himself here.]

- Gave new looks to medical alt, atmospherical alt , engineering alt, command and pilot voidsuits.
- Gave new looks to all Dagon hardsuits except the Chief Engineer. 

x- Removed command_rig as it was a white XO that's neither code-used or icon used anywhere on the map. Less bloat for all.

Sprites done by K'Braid and paid for by me.

### CODE REVIEW

**Comment by Firefox13** [comment]
images pls?
~~icondiffbot shows partially only~~

**Comment by CRISPR-core** [comment]
I'm about to head asleep but will update the pull with some picturettes tomorrow. Damn iconbot...

**Review by wb13 — APPROVED** [review]

**Comment by Sgtwok** [comment]
Are there unathi variants?

**Comment by CRISPR-core** [comment]
The hardsuits never have any variants.

As for the voidsuits... nope - a miss on my part. Consider them added in a future update.

**Comment by Sgtwok** [comment]
The old infantry hardsuits had unathi leg sprites.

**Comment by HawkerTheGreat** [comment]
For anyone curious about the unathi sprites, there is quite a few of them. I never merged it due to the fact I took a six month hiatus. I didn't want to bother with it after I stopped playing, so I closed it.

Here it is for anyone interested. It may need an update, but as of January it was up to date.
https://github.com/VestaOfOrion/Vesta.Bay/pull/334

**Pull request merged**
