### PR TITLE
Changes skillpoints amount from 4 to 8

### PR DESCRIPTION
**Pull request by Agateophobia**
just like in the title, people want it 8, like it was on vestia

### CODE REVIEW

**Comment by Lamasmaster** [comment]
I will just give my take on this, there is a reason you get low amount of skillpoints on bay and its because it leads to powercreep like it did on hestia where everyone has double master skills which considering how strong most of them are isn´t ideal. Again you are not supposed to be master of everything.

**Comment by Agateophobia** [comment]
I honestly would make it 6, but I was too lazy to think while changing two values

**Comment by Vizoplez** [comment]
> I will just give my take on this, there is a reason you get low amount of skillpoints on bay and its because it leads to powercreep like it did on hestia where everyone has double master skills which considering how strong most of them are isn´t ideal. Again you are not supposed to be master of everything.

A majority of combat-orientated roles can already take double master, if not triple. Most security can take double master and basic athletics; sure, they are unable to do anything else; but it didnt solve the issue of min-maxing. Bay already increased the amount weapons expertise costs by a decent bit; restricting skills has only cucked other jobs with inherently low amounts (like bridge officer) to be unable to take max science + mechanical repair skills + athletics

**Comment by BurpleBineapple** [comment]
So. Here's where I get to be the bad man.

Skills are not being adjusted for the near future. Take some time to get used to the new system. We may revisit this once there's been a week or two of playtesting.

For now, no. We're not changing balance. This has been discussed a few times now.

**Pull request closed without merging**
