### PR TITLE
Infantry Sidearms Update

### PR DESCRIPTION
**Pull request by Vizoplez**
Adds infantry sidearm selection, changes lockers and otherwise adds two new guns to facilitate this. All are alertlocked.

### CODE REVIEW

**Comment by Vizoplez** [comment]
Alls fixed. 
image

**Comment by Anton-Kr** [comment]
.454 is strong as fuck and is reserved for the CO for a reason. This at most would be better off being CoS-tier magnum round.

**Comment by Vizoplez** [comment]
> .454 is strong as fuck and is reserved for the CO for a reason. This at most would be better off being CoS-tier magnum round.

Counterpoint: XO and other revolvers actually use the 454 (XO gets the Final Argument, versus the CO's Ultimate argument), though this was taken into consideration

Edit; Counterpoint to my counterpoint, XO's is actually downchambered to 15mm

**Comment by gilvian** [comment]
mmmm, more validhunt tools :)

**Comment by Vizoplez** [comment]
> .454 is strong as fuck and is reserved for the CO for a reason. This at most would be better off being CoS-tier magnum round.

My main thoughts for 454 is that it (supposedly) wasnt the most unique of rounds (2 guns that used it) and the fact it is both:
_Limitingly expensive_ to print, costing ~4x as much per speedloader than magnum 
and
_Needs a jailbroken autolathe to reliably get_

Though its probably going to be used as a PVP tool if I keep it at 454 so to MAGNUM it goes

**Comment by BurpleBineapple** [comment]
> A shiny al-Maliki & Mosley Autococker automatic revolver

> *automatic revolver*
image

Jokes aside, going to put this PR on hold for a while. Might come back to it in the next few days but there's some other changes being made that will conflict with this PR

**Comment by Alanii** [comment]
Sidearms are not needed for infantry.

They should only use their weapons off-ship. I was thinking about giving them access to a smart gun for nonlethal weapons aboard the vessel, but in reality soldiers are not given sidearms unless its in relation to their position, i.e. crew chiefs, crew members. In that case they're generally given a pistol instead of a rifle. It is never both.

I know this is a video game as any other, but giving them multiple weapons seems a little too much firepower for someone who is required to defend exploration off ship.


AFAIK there is a proposal that will be thrown up and pushed through to test the waters regarding a possible rework anyhow.

But if you'd like to change this PR into a "adds sidearm box" PR that is fine.

It hasn't been started on yet, but there is a proposal for antagonist/renegade stuff getting a facelift specifically for extended rounds to replace the boredom infused extended with minor bumps in the road.

When I have a good thorough explanation of how it works and what strings are attached I will talk to developers.

**Comment by Anton-Kr** [comment]
They already get sidearms

**Comment by Vizoplez** [comment]
> Sidearms are not needed for infantry.
> 
> They should only use their weapons off-ship. I was thinking about giving them access to a smart gun for nonlethal weapons aboard the vessel, but in reality soldiers are not given sidearms unless its in relation to their position, i.e. crew chiefs, crew members. In that case they're generally given a pistol instead of a rifle. It is never both.
> 
> I know this is a video game as any other, but giving them multiple weapons seems a little too much firepower for someone who is required to defend exploration off ship.
> 
> AFAIK there is a proposal that will be thrown up and pushed through to test the waters regarding a possible rework anyhow.
> 
> But if you'd like to change this PR into a "adds sidearm box" PR that is fine.
> 
> It hasn't been started on yet, but there is a proposal for antagonist/renegade stuff getting a facelift specifically for extended rounds to replace the boredom infused extended with minor bumps in the road.
> 
> When I have a good thorough explanation of how it works and what strings are attached I will talk to developers.

Alanii. They already have sidearms. If you check the changes, I simply just moved them into a different equipment kit and gave them different options. I agree with your points, but, as it stands; All this does is
1) Move the P10 into a sidearm selection menu
2) Move the new gun (The LEAR90-INF) Into that same selection menu
3) Give the SL a choice between their current weapon, a P10, and a 15mm revolver
Infantry do not get two sidearms; they still have the same amount of guns. This is more of a personal preference thing/ecetera.

**Comment by BurpleBineapple** [comment]
Closing for now due to changes to infantry being made by Alanii.

**Pull request closed without merging**
