### PR TITLE
[WIP] Oh god Oh fuck, it's a Teshari Port

### PR DESCRIPTION
**Pull request by Superhats**
VERY early WIP of a port of Teshari, courtesy of UristMcStation
I am fully expecting it to fail CI as-is

To-do:

- [X] Species code
- [X] Species sprites
- [ ] Culture
- [ ] Items
- [ ] General Balance Sweep
- [ ] Lore

### CODE REVIEW

**Comment by Superhats** [comment]
I know, I didn't #include anything yet

**Comment by ghost** [comment]
sin is being committed, and I'm helping it happen.

**Comment by ghost** [comment]
okay, it seems someone else is already working on this and has been working on it for a while, so this pull is either going to be removed or mixed with their work. for clarity its @greenjoe from discord, they have been working with @limette and have been using another codebase (not Urist) to get this done. this is @Superhats merge so ask him the questions, I'm simply a helping hand in the matter.

**Comment by Superhats** [comment]
Closed since someone else is doing it

**Comment by Sgtwok** [comment]
If this gets actually merged, might as well throw the Kidan in.

**Pull request closed without merging**
