### PR TITLE
Expands Verne Species

### PR DESCRIPTION
**Pull request by BladeburstNINJA**
:cl: 
maptweak: Expands the species available to Verne to include, Skrell, Unathi, Yeosa, Shell, Tajaran, and Genemodder. 
/:cl:

### CODE REVIEW

**Review by Superhats — APPROVED** [review]
Code's alright. Changelog, please.

**Comment by BladeburstNINJA** [comment]
What's the format for the changelog? :cl? And to close?

**Comment by BladeburstNINJA** [comment]
Ok, is the cl in there visible?

**Comment by Superhats** [comment]
No, you need to create an actual changelog file. You'll find instructions in html/changelog

**Comment by BladeburstNINJA** [comment]
Can you send me the direct link? I don't know where to find that.

**Comment by Superhats** [comment]
https://github.com/VestaOfOrion/Vesta.Bay/blob/dev/html/changelogs/__CHANGELOG_README.txt

**Comment by BladeburstNINJA** [comment]
Where do I find the .yml file?

**Comment by Superhats** [comment]
It's under html/changelog. As in, the folder.

**Comment by Superhats** [comment]
https://github.com/VestaOfOrion/Vesta.Bay/tree/dev/html/changelogs

**Comment by BladeburstNINJA** [comment]
Ok, how do I copy this, edit it, and then commit it?

**Comment by Superhats** [comment]
You'll probably have to download the code for this.

**Comment by Superhats** [comment]
It's for paradise but you can find a tutorial here https://www.paradisestation.org/wiki/index.php/Setting_up_TortoiseGit

**Comment by BladeburstNINJA** [comment]
Ok, how is the changelog supposed to look?
maptweak
author: BladeburstNINJA
delete-after: true
  rscadd: "Adds Skrell, Unathi, Yeosa, Shells, Tajaran, and Genemodders to Verne."
?

**Pull request merged**
