### PR TITLE
Glasses for the masses

### PR DESCRIPTION
**Pull request by Pebblesthe2nd**
New glasses, and sunglasses.
Added to loadout.
Current glass sprites minor tweaks to have same tints, scales etc.

https://imgur.com/a/kxGaPPX ( a little outdated, did couple more cycles of tweaks but it gives a good idea of the new stuff)

### CODE REVIEW

**Comment by Pebblesthe2nd** [comment]
Well I got it working, but the prescription sunglasses no longer give visual aid.
Anyone able to help out with resolving it? Should just be a matter of placing a correct path somewhere but I am stumped.

Funny enough I had to do the deletion in row 113   code/modules/client/preference_setup/loadout/lists/eyegear.dm        to make it work, that broke the prescription effect, but you can still spawn with them, they just dont work.

**Comment by wb13** [comment]
> 
> 
> Well I got it working, but the prescription sunglasses no longer give visual aid.
> Anyone able to help out with resolving it? Should just be a matter of placing a correct path somewhere but I am stumped.
> 
> Funny enough I had to do the deletion in row 113 code/modules/client/preference_setup/loadout/lists/eyegear.dm to make it work, that broke the prescription effect, but you can still spawn with them, they just dont work.

Hm, is this still broken?
I just tested locally and prescription sunglasses are working as intended for me.

**Comment by Pebblesthe2nd** [comment]
Well the weird part is I can get it to work locally, but not compiling, so trying various fixes, and it either compiles or works as intended, not both =D.  Think I found a good solution this time though, just need to troubleshoot the paths some more it seems, something fishy going on. Basically made a new var for prescription sunglasses so just a matter of making it load properly now, should have time to solve it later today with a bit of luck.  

EDIT: Actually I will try a rollback too and take another look at it, in case I solved the issue with the last one but forgot. Dont have the time to do it right now

**Comment by Pebblesthe2nd** [comment]
Holy %"%"%  it passed. It works on my local server too.

**Review by BurpleBineapple — APPROVED** [review]

**Pull request merged**
