### PR TITLE
Revert "Inflatables, unpowered doors and firedoors can no longer be closed on people." and related stuff.

### PR DESCRIPTION
**Pull request by Firefox13**
изображение

### CODE REVIEW

**Comment by Keekenox** [comment]
Blessed.

**Comment by Firefox13** [comment]
The runtime reacts to voxship-1.dmm and during the test it flat out refuses to load up. On baystation there were no problems with it, and now I don't know what causes it. I will work later on it ~~until someone helps me with it~~

**Comment by Anton-Kr** [comment]
Vox map was iirc changed to accommodate this change. My suggestion is to remove the vox asteroid base as the ship is already a better map for Vox anyway.

**Review by BurpleBineapple — APPROVED** [review]
Approved

**Pull request merged**
