### PR TITLE
Shitcode Speedrun Master CQC, 50:04 WR

### PR DESCRIPTION
**Pull request by PSTMRTM**
Master CQC for all jobs + lots of other buffs to other skills except athletics, because I forgot to make the change, the speedrun focus was on CQC so yeah.

Link to proof of it working: https://media.discordapp.net/attachments/762930148101849110/804058771432144936/unknown.png?width=646&height=670

"I hereby decree if someone makes a PR to remove all skill locks and throw the server into fuck all balance, I will speedmerge it"

### CODE REVIEW

**Comment by HawkerTheGreat** [comment]
First good code I've seen in a long while. Also, don't forget your changelog. Good to speedmerge for live testing. 👍

**Comment by XElectricX** [comment]
Allah has blessed this repo with this PR.

**Comment by io-util** [comment]
If you're actually serious about this, add a changelog at the very least.

**Comment by io-util** [comment]
Stale, reopen and fix if you are actually serious.

**Pull request closed without merging**
