### PR TITLE
Ports SSV items from Vesta, SSV Rework. (Soon.tm)

### PR DESCRIPTION
**Pull request by Kaksisilma**
This PR adds a new SSV (Skrell Scout Ship) along with numerous tweaks to already-existing weapons and items, aswell as porting some old stuff from old Hestia.

Big thanks to Memed Hans for the skrellian shield sprites, Lamamaster for the original QX-2 sprite, and Rowtree for some ideas with the interior of the ship, along with everyone on the dev channel who helped me debug it.

1showcase

A list of changes will be included in the changelog, but the most notable ones are:
 - Porting of Vesta's QX-2 as a miniaturized railgun
 - Addition of skrellian shields
 - Completely new SSV and SSV-S
 - Some damage adjustments to the energy machete. (Same as E-sword now)
 - Porting of Vesta's SSV Rig armor values and sprites
 - Porting of Vesta's SSV gas tanks and powercell sprites
 - Minor name-related tweaks to all SSV firearms.
 
This is mostly complete but I will keep it in draft for a while longer to make sure I didn't miss anything.

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
now, alongside being able to abuse them from range, skrell cops have the advanced technological capability to assault simplemobs at melee distance. It was fun collaborating on this, hope to be able to sprite more fishman stuff in the future.

**Comment by BurpleBineapple** [comment]
It seems like you've done something odd with the map? I can't find any skrellship map, but you deleted the existing one.

**Comment by Kaksisilma** [comment]
> It seems like you've done something odd with the map? I can't find any skrellship map, but you deleted the existing one.

No clue why's the diff so large. It's working fine though and even CI ran over it.

**Comment by Kaksisilma** [comment]
Should be good for review/merge.

**Review by BurpleBineapple — APPROVED** [review]

**Pull request merged**
