### PR TITLE
Coup de Grace on tan/urban

### PR DESCRIPTION
**Pull request by BurpleBineapple**
🆑 
rscdel: Removes most of the rest of tan/urban accessories
tweak: Restricts all UBAC/pouches/plate carriers to UNIFORMED_BRANCHES. Grey plate carriers are for civilians.
/🆑

### CODE REVIEW

**Comment by ShaSCT** [comment]
why

**Comment by bearrrrrrrr** [comment]
why

**Comment by Sgtwok** [comment]
Nobody asked for this.

**Comment by listerla** [comment]
cringe

**Pull request merged**
