### PR TITLE
Stun beam color

### PR DESCRIPTION
**Pull request by Alejodbort2**
-Adds a diferent beam color for Stun mode.

image

## Changelog
:cl:
tweak: Shock and Stun now have differents beams.
/:cl:

### CODE REVIEW

**Review by Superhats — APPROVED** [review]
Just needs a changelog.

**Comment by Superhats** [comment]
However, it may look a tad too similar to the ascent's particle beams.

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
It's also very similar to pulse weapons, which could be an issue. People are used to the "electricity" look of stun guns.

The colour I think is alright, but the actual beam should preferably stay the same shape

**Comment by BurpleBineapple** [comment]
Also missing a changelog

**Comment by Alejodbort2** [comment]
> However, it may look a tad too similar to the ascent's particle beams.

Yes , it's the Ascent's particle beams. Thats what Stun it's, a blue beam.


> It's also very similar to pulse weapons, which could be an issue. People are used to the "electricity" look of stun guns.
> 
> The colour I think is alright, but the actual beam should preferably stay the same shape

And about that, I can give im a "electricity" look like the stun gun, but it doesn't look good, or feel good, if you contrast the smooth sound of firing a Stun charge with the all-crazy blue "electric" shot. Maybe just me, there you have a little WIP its you prefer a "electricity" beam and I start doing it.

image

**Comment by BurpleBineapple** [comment]
The issue with that is giving the human faction the same weapon particle as the hyper advanced Ascent. *Personally* I think changing the particle for a common weapon is going to confuse people in game rather than improve the feature.

**Comment by Superhats** [comment]
Yeah. At this point, changing that for the sake of changing will just get people confused. Stun beams are really just lower intensity shock beams, it makes sense they'd be the same color.

**Pull request closed without merging**
