### PR TITLE
Expands Verne and Salvage Gantry Species

### PR DESCRIPTION
**Pull request by BladeburstNINJA**
Adds Skrell, Unathi, Yeosa, Shells, Tajarans, and Genemodders to Verne and Salvage Gantry.

### CODE REVIEW

**Comment by BurpleBineapple** [comment]
Gantry was designed to be a cheap, ragtag human salvage vessel, and might not have the correct equipment for suit cycling on these species. I'll take a look at the map before we consider adding this.

Second, more just a personal opinion, but I feel like turning the one human-exclusive offship into another Bearcat isn't the best for variety. I'll still look through but personally I think the bearcat already accomplishes what this PR is trying to do.

**Comment by BladeburstNINJA** [comment]
I can understand the argument for the Gantry, but the Verne prior to the rebase did have more species.

**Comment by Superhats** [comment]
I'm fine with Verne having more variety, but as said above, the Gantry is honestly fine as-is. I'll suggest separating the two changes.

**Comment by BladeburstNINJA** [comment]
Yea, I can close the commit and split it into two.

**Comment by anconfuzedrock** [comment]
Prior to the rebase the verne had more species, but prior to the rebase the verne was an entirely different vessel- a few months ago it got radically updated with being human and ipc only in mind. Best make sure it can fit nonhumans first.

**Comment by BladeburstNINJA** [comment]
I mean, the main difference between fitting humans and non human species is mostly suits? As long as there are soft suits and differing MREs multiple species on the Verne should be doable. Maybe not optimal but doable.

**Pull request closed without merging**
